---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - github.dana.io
  resources:
  - issues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.dana.io
  resources:
  - issues/finalizers
  verbs:
  - update
- apiGroups:
  - github.dana.io
  resources:
  - issues/status
  verbs:
  - get
  - patch
  - update
