apiVersion: dana.io.dana.io/v1alpha1
kind: GithubIssue
metadata:
  labels:
    app.kubernetes.io/name: githubissue
    app.kubernetes.io/managed-by: kustomize
  name: githubissue-sample
spec:
  # TODO(user): Add fields here
